name: bot_toast_lego
description: "lego that bot_toast apply to your project"
#publish_to: 'none'
repository: https://github.com/flutter-lego/bot_toast_lego

version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: #@add
  flutter_svg: #@add
  gap: #@add
  june_flow_util:
  styled_widget: #@add
  modal_bottom_sheet: #@add
  keyboard_attachable: #@add
  flutter_zoom_drawer: #@add
  bot_toast: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true